--- #YAML:1.0
name:               Lexical-Persistence
version:            1.020
abstract:           Persistent, continuation-like contexts for lexical variables.
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Devel::LexAlias:  0.04
    PadWalker:        1.1
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/rcaputo/lexical-persistence
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
